name: remote_logging_handlers
description: Logging handlers for logz and loki.
version: 0.0.1
author: Herbert Poul
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pedantic: '1.5.0'
  logging: ^0.11.3+2
  dio: ^2.0.0
  rxdart: ^0.20.0
  intl: ^0.15.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
