name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 0.2.0
author: Herbert Poul <herbert@poul.at>
homepage: https://github.com/hpoul/logging_appenders

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: '>=1.0.0 <2.0.0'
  logging: '>=0.11.3+2 <1.0.0'
  dio: '>=2.1.0 <3.0.0'
  rxdart: '>=0.20.0 <1.0.0'
  intl: '>=0.15.0 <1.0.0'
  clock: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: ">=1.5.0 <2.0.0"
  pedantic: '>=1.5.0 <2.0.0'

# The following section is specific to Flutter.
flutter:
